-- =========================================
-- SCHEMA: MVC DB (H2 file)
-- =========================================

DROP TABLE IF EXISTS purchase_lines;
DROP TABLE IF EXISTS purchases;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

-- ---------- ROLES ----------
CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(40) NOT NULL UNIQUE,
                       description VARCHAR(100)
);

-- ---------- USERS ----------
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(40) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       full_name VARCHAR(100),
                       email VARCHAR(50) NOT NULL UNIQUE,
                       enabled BOOLEAN NOT NULL DEFAULT TRUE,

                       role_id BIGINT NOT NULL,

                       CONSTRAINT fk_users_role
                           FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- Índice opcional (útil si filtras / buscas por role)
CREATE INDEX idx_users_role_id ON users(role_id);

-- ---------- PURCHASES ----------
CREATE TABLE purchases (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           created_at TIMESTAMP NOT NULL,
                           username VARCHAR(50) NOT NULL,
                           total_amount DECIMAL(12,2) NOT NULL
);

CREATE INDEX idx_purchases_username ON purchases(username);
CREATE INDEX idx_purchases_created_at ON purchases(created_at);

-- ---------- PURCHASE_LINES ----------
CREATE TABLE purchase_lines (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                purchase_id BIGINT NOT NULL,

                                ticket_type_code VARCHAR(80) NOT NULL,
                                ticket_name_snapshot VARCHAR(30) NOT NULL,
                                unit_price_snapshot DECIMAL(10,2) NOT NULL,

                                qty INT NOT NULL,
                                line_total DECIMAL(12,2) NOT NULL,

                                CONSTRAINT fk_purchase_lines_purchase
                                    FOREIGN KEY (purchase_id) REFERENCES purchases(id)
);

CREATE INDEX idx_purchase_lines_purchase_id ON purchase_lines(purchase_id);
